/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Thu Feb 22 15:44:39 2018. */

#include "mblue.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t dl_rpc_header_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, dl_rpc_header, method_name, method_name, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_rpc_header, layout_index, method_name, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_array_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, dl_array, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_at_request_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_at_request, at_set, at_set, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_at_request, cmd_index, at_set, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, CALLBACK, OTHER, dl_at_request, data, cmd_index, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_uart_request_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_uart_request, com, com, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, dl_uart_request, data, com, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_uart_response_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_uart_response, len, len, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_mblue_message_fields[7] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, dl_mblue_message, magic, magic, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, dl_mblue_message, info, magic, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, dl_mblue_message, code, info, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, CALLBACK, OTHER, dl_mblue_message, src, code, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, CALLBACK, OTHER, dl_mblue_message, dst, src, 0),
    PB_FIELD(  6, BYTES   , REQUIRED, CALLBACK, OTHER, dl_mblue_message, data, dst, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_1_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_1, num, num, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_11_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_11, num1, num1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_11, num2, num1, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_111_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_111, num1, num1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_111, num2, num1, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, dl_111, num3, num2, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_1111_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_1111, num1, num1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_1111, num2, num1, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, dl_1111, num3, num2, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, dl_1111, num4, num3, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_12_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_12, num, num, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, dl_12, data, num, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_112_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_112, num1, num1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_112, num2, num1, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, CALLBACK, OTHER, dl_112, data, num2, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_113_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_113, num1, num1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_113, num2, num1, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, dl_113, data, num2, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_1112_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_1112, num1, num1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_1112, num2, num1, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, dl_1112, num3, num2, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, CALLBACK, OTHER, dl_1112, data, num3, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_server_init_fields[8] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, dl_server_init, channel, channel, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, dl_server_init, product, channel, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, dl_server_init, device_type, product, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, dl_server_init, device_id, device_type, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, dl_server_init, imei, device_id, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, dl_server_init, iccid, imei, 0),
    PB_FIELD(  7, STRING  , REQUIRED, STATIC  , OTHER, dl_server_init, firmware_version, iccid, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_server_touch_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_server_touch, lng, lng, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_server_touch, lat, lng, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, dl_server_touch, satellites, lat, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, dl_server_touch, power, satellites, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, dl_server_touch, rssi, power, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, dl_server_touch, interval, rssi, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, dl_server_touch, type, interval, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, dl_server_touch, acc, type, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_server_event_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_server_event, type, type, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, dl_server_event, value, type, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_server_setup_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_server_setup, key, key, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, dl_server_setup, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t dl_ack_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, dl_ack, ack, ack, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, dl_ack, seq, ack, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
