set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "i386")
set(CMAKE_SYSTEM_VERSION gnu)
if(NOT ${CMAKE_C_COMPILER})
  set(CMAKE_C_COMPILER gcc)
endif()

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -m32" CACHE STRING "c flags")

